source :rubygems

gem 'awesome_print'
gem 'nokogiri'
gem 'padrino'
gem 'json'
gem 'pry'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'rubyzip'
gem 'progressbar'
gem 'datamapper'
gem 'dm-mysql-adapter'
gem 'thor'
gem 'dm-geokit'
gem 'representative'
gem 'picky'
gem 'redis'
#gem 'fastercsv', :require => 'csv'
