source :rubygems

gem 'awesome_print'
gem 'nokogiri'
gem 'padrino'
gem 'json'
gem 'pry'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'rubyzip'
gem 'progressbar'
gem 'datamapper'
gem 'dm-mysql-adapter'
gem 'thor'
gem 'representative'
gem 'rack-cache'
gem 'picky'
gem 'yajl-ruby', :require => 'yajl'
#gem 'dm-geokit'
